name: env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6.0
  - numpy=1.23.1
  - pandas=1.4.3
  - matplotlib=3.2.2
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - pillow=6.2.2
  - tensorboard=2.10.0
  - pytorch-lightning=1.7.1
  - ipykernel=6.21.2
  - jupyter_client=7.4.9
  - jupyter_core=4.12.0
  - pip=22.2.2
  - setuptools=59.5.0
  - wheel=0.37.1
  - mkl=2021.4.0
  - h5py=3.7.0
  - pyyaml=6.0
  - fsspec=2022.7.1
  - packaging=21.3
  - tqdm=4.64.0
  - einops=0.7.0
  - omegaconf=2.3.0
  - torchmetrics=0.9.3
  - aiohttp=3.8.1
  - brotlipy=0.7.0
  - click=8.1.3
  - cryptography=37.0.4
  - future=0.18.2
  - grpcio=1.46.3
  - importlib-metadata=4.11.4
  - markupsafe=2.1.1
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - numexpr=2.8.3
  - protobuf=3.19.4
  - psutil=5.9.4
  - pydeprecate=0.3.2
  - pyopenssl=22.0.0
  - requests=2.28.1
  - six=1.16.0
  - typing_extensions=4.3.0
  - werkzeug=2.2.2
  - zipp=3.8.1
  - absl-py=1.2.0
  - attrs=22.1.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.1.0
  - colorama=0.4.5
  - idna=3.3
  - oauthlib=3.2.0
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - pytz=2022.1
  - urllib3=1.26.11